title: 欢迎来到Fighttinggi的Github
author: Fighttinggi
email: wangyoujie2021@163.com
description: > # this means to ignore newlines until "baseurl:"
  学习！！

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: Fighttinggi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
