title: Welcome Fighttinggi Github
author: Fighttinggi
email: Fighttinggi@Github.com
description: > # this means to ignore newlines until "baseurl:"
  Study!!!
# social links
twitter_username: Fighttinggi # DO NOT include the @ character, or else the build will fail!
github_username:  Fighttinggi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
